version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: webapp-postgres
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webapp-network

  backend:
    build: ./backend
    container_name: webapp-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - webapp-network

  frontend:
    build: ./frontend
    container_name: webapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

volumes:
  postgres-data:
